[tool.poetry]
name = "Heleus"
version = "2.0.0"
description = "A Discord bot forked from Liara. Built on disnake."
authors = ["derpychap <derpy@duck.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
uvloop = "^0.17.0"
dill = "^0.3.6"
raven = "^6.10.0"
strictyaml = "^1.6.2"
tabulate = "^0.9.0"
psutil = "^5.9.4"
disnake = {extras = ["voice"], version = "^2.7.0"}
coredis = {extras = ["hiredis"], version = "^4.9"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"