[tool.poetry]
name = "Heleus"
version = "2.0.0"
description = "A Discord bot forked from Liara. Built on disnake."
authors = ["derpychap <derpy@duck.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
uvloop = "^0.16.0"
dill = "^0.3.5"
raven = "^6.10.0"
strictyaml = "^1.6.1"
tabulate = "^0.8.10"
psutil = "^5.9.1"
disnake = {extras = ["voice"], version = "^2.5.1"}
coredis = {extras = ["hiredis"], version = "^4.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"