[tool.poetry]
name = "Heleus"
version = "2.0.0"
description = "A Discord bot forked from Liara. Built on disnake."
authors = ["derpychap <holla@derpychap.co.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
uvloop = "^0.16.0"
dill = "^0.3.4"
raven = "^6.10.0"
strictyaml = "^1.6.1"
tabulate = "^0.8.9"
psutil = "^5.9.0"
disnake = {extras = ["voice"], version = "^2.4.0"}
coredis = {extras = ["hiredis"], version = "^3.1.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
